services:
  nginx:
    container_name: "php_nginx"
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    volumes:
      - .:/var/www
    ports:
      - 80:80
    command: ["./dockerfiles/nginx/start.sh"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rent_pro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
