services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rent_pro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
